export type ServiceInfo = {
  title: string;
  slug: string;
  label: string;
  image: string;
  heroImage: string;
  summary: string;
  introTitle: string;
  intro: string[];
  benefits: string[];
  checklist: string[];
  includes: string[];
  faqs: { question: string; answer: string }[];
};

const baseFaqs = (label: string) => [
  {
    question: `How quickly can I hire ${label.toLowerCase()} support?`,
    answer:
      "Most requirements are reviewed the same day. Availability depends on your location, timing, duties, and whether you need full-time or part-time support.",
  },
  {
    question: "Does BB HOSPITALITY verify candidates?",
    answer:
      "Yes. We follow identity checks, document screening, experience review, and basic reference checks before suggesting profiles.",
  },
  {
    question: "Can I request a replacement?",
    answer:
      "Yes. Our support team helps with replacement assistance based on your service plan and the terms agreed during booking.",
  },
];

export const serviceCategories: ServiceInfo[] = [
  {
    title: "Maid Services",
    slug: "maid",
    label: "Maid",
    image: "/Service_Card_1.png",
    heroImage: "/GettyImages-1456829834.webp",
    summary: "Verified house maids for cleaning, cooking assistance, laundry, and daily household work.",
    introTitle: "House Maid Services In Mumbai",
    intro: [
      "If you are having trouble managing your house in Mumbai's fast-paced schedule, BB HOSPITALITY helps you hire trained maids for reliable daily support. Our service is designed for families, working professionals, senior citizens, and busy households who need dependable assistance at home.",
      "We provide full-time and part-time maid options for cleaning, dusting, mopping, dish washing, laundry, utensil cleaning, grocery assistance, and other routine household duties. Every suggested candidate is reviewed for experience, reliability, and suitability before profile sharing.",
      "As a trusted hospitality staffing partner, BB HOSPITALITY focuses on safety, documentation, service flexibility, and clear communication so you can hire with confidence and keep your home well-managed.",
    ],
    benefits: [
      "Full-time, part-time, and live-in maid options",
      "Candidate screening and profile shortlisting",
      "Flexible duties based on your household routine",
      "Replacement support as per service terms",
      "Dedicated coordination before and after joining",
    ],
    checklist: [
      "Experience in household work",
      "Background verification and identity documents",
      "Cooking, cleaning, childcare, or elder-care skills",
      "Timing flexibility and weekly off expectations",
      "Customer reviews and agency reputation",
    ],
    includes: [
      "Household Works",
      "Dish Washing",
      "Utensil Cleaning",
      "Laundry",
      "Clothes Ironing",
      "Cooking Assistance",
      "Grocery Shopping",
      "Floor Mopping",
      "Cobweb Removal",
      "Bathroom Cleaning",
      "Dusting and more as per need",
    ],
    faqs: baseFaqs("maid"),
  },
  {
    title: "Cook Services",
    slug: "cook",
    label: "Cook",
    image: "/Service_Card_2.png",
    heroImage: "/GettyImages-1350786822-1.webp",
    summary: "Experienced home cooks for daily meals, family menus, diet preferences, and kitchen support.",
    introTitle: "Cook Services In Mumbai",
    intro: [
      "BB HOSPITALITY helps families hire reliable cooks for fresh, timely, and hygienic meals at home. Whether you need breakfast preparation, lunch packing, dinner service, or special diet support, we shortlist profiles based on your cuisine preferences.",
      "Our cooks can support vegetarian, non-vegetarian, regional, basic diet, and family-style meal requirements. We help you discuss timings, number of meals, kitchen expectations, and responsibilities clearly before joining.",
      "The focus is simple: dependable cooking help, transparent coordination, and a better daily routine for your household.",
    ],
    benefits: ["Cuisine preference matching", "Daily or shift-based cooking", "Meal planning support", "Hygiene-focused candidates", "Replacement assistance"],
    checklist: ["Cuisine experience", "Kitchen hygiene habits", "Meal count and timings", "Family size", "Special diet requirements"],
    includes: ["Breakfast preparation", "Lunch and dinner", "Tiffin packing", "Vegetable cutting", "Kitchen cleanup", "Basic grocery coordination"],
    faqs: baseFaqs("cook"),
  },
  {
    title: "Baby Care & Delivery Service",
    slug: "baby-care-delivery-service",
    label: "Baby Care & Delivery Service",
    image: "/Get_a_Quote.png",
    heroImage: "/GettyImages-1226346559-1.webp",
    summary: "Reliable baby-care support for childcare, newborn routines, post-delivery assistance, and family care needs.",
    introTitle: "Baby Care & Delivery Service In Mumbai",
    intro: [
      "Finding dependable baby-care and post-delivery support is one of the most important decisions for any family. BB HOSPITALITY helps parents connect with caring attendants who can support daily child supervision, newborn routines, and mother-care needs.",
      "Candidates can assist with feeding reminders, play supervision, baby bath support, massage routines, hygiene care, and post-delivery household support as per your instructions.",
      "We prioritize trust, patience, newborn experience, and clear expectations so families can feel comfortable with the support they hire.",
    ],
    benefits: ["Child and newborn routine support", "Shortlisted experienced profiles", "Flexible hours", "Parent-led duty planning", "Reliable replacement support"],
    checklist: ["Childcare and newborn experience", "Age-group comfort", "Timing and holiday needs", "Feeding, massage, and hygiene duties", "Emergency contact process"],
    includes: ["Child supervision", "Feeding assistance", "Baby massage", "Baby bath support", "Mother assistance", "Basic baby laundry"],
    faqs: baseFaqs("baby care and delivery service"),
  },
  {
    title: "Patient Care Services",
    slug: "patient-care",
    label: "Patient Care",
    image: "/GettyImages-1226346559-1.webp",
    heroImage: "/GettyImages-1226346559-1.webp",
    summary: "Patient attendants for recovery support, daily assistance, mobility help, and care coordination.",
    introTitle: "Patient Care Services In Mumbai",
    intro: [
      "BB HOSPITALITY helps families hire patient-care attendants for home recovery, post-hospital assistance, mobility support, and daily care routines.",
      "The service is ideal for patients who need help with meals, movement, reminders, personal care support, and family coordination.",
      "We help clarify duties carefully so the attendant's responsibilities match the patient's condition and household expectations.",
    ],
    benefits: ["Male and female attendant options", "Day and night shift support", "Recovery routine assistance", "Mobility and meal support", "Family coordination"],
    checklist: ["Patient condition", "Shift duration", "Mobility needs", "Personal care duties", "Medical supervision requirement"],
    includes: ["Meal assistance", "Mobility support", "Medicine reminders", "Personal care support", "Companionship", "Basic room hygiene"],
    faqs: baseFaqs("patient care"),
  },
  {
    title: "Elder Care Services",
    slug: "elder-care",
    label: "Elder Care",
    image: "/GettyImages-1350786822-1.webp",
    heroImage: "/GettyImages-1350786822-1.webp",
    summary: "Compassionate elder-care attendants for companionship, routine help, and daily living support.",
    introTitle: "Elder Care Services In Mumbai",
    intro: [
      "Elder-care support requires patience, respect, and consistency. BB HOSPITALITY helps families hire attendants who can assist senior citizens with daily routines and companionship.",
      "Support may include meal assistance, walking support, medicine reminders, hygiene assistance, and coordination with family members.",
      "Our approach keeps seniors comfortable while helping families manage care with greater confidence.",
    ],
    benefits: ["Companionship support", "Daily routine assistance", "Day or night options", "Polite and patient candidates", "Family coordination"],
    checklist: ["Senior's mobility level", "Medical routine", "Meal and hygiene needs", "Shift timing", "Language comfort"],
    includes: ["Walking support", "Meal assistance", "Medicine reminders", "Companionship", "Personal care", "Room organization"],
    faqs: baseFaqs("elder care"),
  },
  {
    title: "Driver Services",
    slug: "driver",
    label: "Driver",
    image: "/GettyImages-1456829834.webp",
    heroImage: "/Hero_Background_Image.png",
    summary: "Professional drivers for family, office, daily commute, and flexible travel requirements.",
    introTitle: "Driver Services In Mumbai",
    intro: [
      "BB HOSPITALITY helps you hire professional drivers for personal, family, and business travel. Profiles are shortlisted based on driving experience, route familiarity, timing, and vehicle comfort.",
      "Whether you need a daily driver, replacement driver, office commute support, or occasional travel assistance, we help define the duty clearly before joining.",
      "Our service keeps reliability, punctuality, and professional conduct at the center of the hiring process.",
    ],
    benefits: ["Full-time and part-time drivers", "Route experience matching", "Family and office use", "Document review", "Replacement support"],
    checklist: ["Driving license", "Route familiarity", "Vehicle type experience", "Timing and overtime terms", "Behavior and punctuality"],
    includes: ["Daily commute", "Family driving", "Office duty", "Airport pickup", "Vehicle care basics", "Outstation discussion"],
    faqs: baseFaqs("driver"),
  },
  {
    title: "Nursing Services",
    slug: "nursing",
    label: "Nursing",
    image: "/GettyImages-1724689200.webp",
    heroImage: "/GettyImages-1724689200.webp",
    summary: "Nursing support for home care routines, supervised recovery, and medical assistance coordination.",
    introTitle: "Nursing Services In Mumbai",
    intro: [
      "BB HOSPITALITY supports families looking for nursing assistance at home for recovery, elderly care, and supervised medical routines.",
      "Nursing requirements are discussed carefully, including shift duration, doctor's instructions, patient condition, and family expectations.",
      "We help you connect with suitable profiles while keeping safety, clarity, and comfort at the center.",
    ],
    benefits: ["Day and night shift options", "Patient routine support", "Family coordination", "Experience-based shortlisting", "Clear duty planning"],
    checklist: ["Doctor instructions", "Patient condition", "Shift timing", "Medical duties required", "Emergency plan"],
    includes: ["Vitals assistance", "Medication reminders", "Patient observation", "Dressing support discussion", "Mobility help", "Family updates"],
    faqs: baseFaqs("nursing"),
  },
  {
    title: "Delivery Services",
    slug: "delivery",
    label: "Delivery",
    image: "/Service_Card_2.png",
    heroImage: "/GettyImages-1456829834.webp",
    summary: "Delivery staff for local business, office errands, household logistics, and daily movement support.",
    introTitle: "Delivery Staff Services In Mumbai",
    intro: [
      "BB HOSPITALITY helps businesses and households hire delivery staff for local errands, movement of packages, office tasks, and routine logistics.",
      "Candidates are shortlisted based on timing, local-area familiarity, communication, and responsibility.",
      "The service is suitable for small businesses, apartments, offices, and families needing dependable daily logistics support.",
    ],
    benefits: ["Local-area staff", "Flexible timing", "Business and household support", "Profile screening", "Clear duty setup"],
    checklist: ["Area knowledge", "Vehicle requirement", "Timing", "Package type", "Reporting process"],
    includes: ["Local deliveries", "Office errands", "Document movement", "Grocery pickup", "Parcel coordination", "Daily logistics"],
    faqs: baseFaqs("delivery"),
  },
  {
    title: "Security Guard Services",
    slug: "security-guard",
    label: "Security Guard",
    image: "/GettyImages-1226346559-1.webp",
    heroImage: "/GettyImages-1226346559-1.webp",
    summary: "Security guards for residential buildings, offices, events, and commercial premises.",
    introTitle: "Security Guard Services In Mumbai",
    intro: [
      "BB HOSPITALITY provides security guard staffing support for residential complexes, offices, retail spaces, and commercial sites.",
      "We help define shift timing, gate duties, visitor management, reporting expectations, and site-specific requirements.",
      "The goal is professional, alert, and accountable security support that fits your premises.",
    ],
    benefits: ["Day and night shifts", "Residential and commercial guards", "Visitor-management support", "Document screening", "Supervisor coordination"],
    checklist: ["Site type", "Shift duration", "Visitor process", "Uniform requirement", "Reporting structure"],
    includes: ["Gate duty", "Visitor entry", "Patrolling", "Delivery monitoring", "Incident reporting", "Parking coordination"],
    faqs: baseFaqs("security guard"),
  },
  {
    title: "Housekeeping Services",
    slug: "housekeeping",
    label: "Housekeeping",
    image: "/GettyImages-1456829834.webp",
    heroImage: "/GettyImages-1456829834.webp",
    summary: "Housekeeping teams for apartments, offices, societies, clinics, and hospitality spaces.",
    introTitle: "Housekeeping Services In Mumbai",
    intro: [
      "BB HOSPITALITY offers housekeeping staffing support for homes, offices, apartments, clinics, retail sites, and hospitality spaces.",
      "We help plan duties like sweeping, mopping, dusting, washroom cleaning, pantry support, common-area upkeep, and scheduled deep-clean coordination.",
      "Our housekeeping process focuses on punctuality, hygiene, supervision, and professional presentation.",
    ],
    benefits: ["Trained housekeeping staff", "Residential and commercial support", "Daily and shift-based teams", "Supervisor coordination", "Hygiene-focused process"],
    checklist: ["Site size", "Daily duties", "Shift timing", "Cleaning material responsibility", "Supervisor needs"],
    includes: ["Floor cleaning", "Dusting", "Washroom cleaning", "Pantry support", "Common area upkeep", "Waste coordination"],
    faqs: baseFaqs("housekeeping"),
  },
  {
    title: "Office Support Services",
    slug: "office-support",
    label: "Office Support",
    image: "/GettyImages-1350786822-1.webp",
    heroImage: "/GettyImages-1350786822-1.webp",
    summary: "Office boys, pantry staff, support attendants, and daily operations help for workplaces.",
    introTitle: "Office Support Services In Mumbai",
    intro: [
      "BB HOSPITALITY helps companies hire office support staff for day-to-day operational assistance, pantry work, errands, guest support, and workplace upkeep.",
      "The service is useful for offices, clinics, coworking spaces, showrooms, and business centers that need disciplined support staff.",
      "We coordinate duties, timing, dress code, and reporting expectations before candidates join.",
    ],
    benefits: ["Office boys and pantry staff", "Professional workplace support", "Flexible shifts", "Document screening", "Replacement coordination"],
    checklist: ["Office size", "Pantry duties", "Errand requirements", "Dress code", "Reporting manager"],
    includes: ["Pantry support", "Guest assistance", "Document movement", "Office errands", "Basic housekeeping", "Meeting room setup"],
    faqs: baseFaqs("office support"),
  },
];

export const serviceLocations = [
  "Maid Services In Malad",
  "Maid Services In Andheri",
  "Maid Services In Mira Road",
  "Maid Services In Mahim",
  "Maid Services In Bandra",
  "Maid Services In Santacruz",
  "Maid Services In Vile Parle",
  "Maid Services In Jogeshwari",
  "Maid Services In Goregaon",
  "Maid Services In Kandivali",
  "Maid Services In Borivali",
  "Maid Services In Dahisar",
  "Maid Services In Bhayandar",
  "Maid Services In Vasai",
  "Maid Services In Virar",
  "Baby Care & Delivery Service In Malad",
  "Baby Care & Delivery Service In Andheri",
  "Baby Care & Delivery Service In Mira Road",
  "Baby Care & Delivery Service In Mahim",
  "Baby Care & Delivery Service In Bandra",
  "Baby Care & Delivery Service In Santacruz",
  "Baby Care & Delivery Service In Vile Parle",
  "Baby Care & Delivery Service In Jogeshwari",
  "Baby Care & Delivery Service In Goregaon",
  "Baby Care & Delivery Service In Kandivali",
  "Baby Care & Delivery Service In Borivali",
  "Baby Care & Delivery Service In Dahisar",
  "Baby Care & Delivery Service In Bhayandar",
  "Baby Care & Delivery Service In Vasai",
  "Baby Care & Delivery Service In Virar",
  "Baby Care & Delivery Service In Haji Ali",
  "Cook Services In Malad",
  "Cook Services In Andheri",
  "Cook Services In Mira Road",
  "Cook Services In Mahim",
  "Cook Services In Bandra",
  "Cook Services In Santacruz",
  "Cook Services In Vile Parle",
  "Cook Services In Jogeshwari",
  "Cook Services In Goregaon",
  "Cook Services In Kandivali",
  "Cook Services In Borivali",
  "Cook Services In Dahisar",
  "Cook Services In Bhayandar",
  "Cook Services In Vasai",
  "Cook Services In Virar",
];

export function getServiceBySlug(slug: string) {
  return serviceCategories.find((service) => service.slug === slug);
}
